---
title: "Homework week 6"
output:
  html_document:
    df_print: paged
---

## creating a dataframe form tsv file
```{r}
mygenes <- read.table('~/gene_dist_head.tsv',header = TRUE, sep = "\t")
mygenes
```

## summary of the dataframe mygenes
```{r}
summary(mygenes)
genes_summary <- data.frame(unclass(summary(mygenes)), check.names = FALSE, stringsAsFactors = FALSE, row.names = NULL)
genes_summary
```

## information about our columns and rows
```{r}
colnames(mygenes)
head(rownames(mygenes), 50)
```

## subsetting data
```{r}
print(head(mygenes[,c(2,4)], 50))
print(head(mygenes[,c(2:4)], 50))
print(head(mygenes[mygenes$chr == 1, c(1:5)], 50))
```

## number of categories in categorical data
```{r}
print(levels(mygenes$chr))
```

## creating a graph with a subset of data and then making interactive plots
```{r}
#install.packages("ggplot2") The intsall libraries have been commented out but the '#' symbol
#install.packages("plotly")  can be removed to install if not already installed 
library(ggplot2) # We load in libraries
library(plotly)
# We define a factor set of autosomes
autosomes<-c("1","2","3","4","5","6","7","8","9","10",
 "11","12","13","14","15","16","17","18","19","20","21","22")  
# We create a new dataframe called 'genes' which only has autosomes, however we still have those additional factors
genes<- mygenes[ which(mygenes$chr %in% autosomes), ] 
genes
# We remove the factors and then order them so they are numerical order and not alphabetical
genes$chr <- factor(genes$chr, levels = autosomes) 
 # We plot in ggplot 
p<-ggplot(data = genes) +  geom_bar(mapping = aes(x = chr, fill = feature), width = 1)
ggplotly(p)
ggplot(data = genes) + geom_bar(mapping = aes(x = chr, fill = feature), width = 1) + coord_polar()
```



